;	TITLE	BBC BASIC (C) R.T.RUSSELL 1981-2024
;
;RAM MODULE FOR BBC BASIC INTERPRETER
;FOR USE WITH VERSION 5.0 OF BBC BASIC
;(C) COPYRIGHT R.T.RUSSELL 1981-2024
;

	SECTION BASICRAM
	
	GLOBAL	ACCS
	GLOBAL	BUFFER
	GLOBAL	ONERSP
	GLOBAL	LIBASE
	GLOBAL	PAGE
	GLOBAL	LOMEM
	GLOBAL	FREE
	GLOBAL	HIMEM
	GLOBAL	RANDOM
	GLOBAL	COUNT
	GLOBAL	WIDTH
	GLOBAL	ERL
	GLOBAL	ERR
	GLOBAL	ERRTRP
	GLOBAL	ERRTXT
	GLOBAL	TRACEN
	GLOBAL	AUTONO
	GLOBAL	INCREM
	GLOBAL	LISTON
	GLOBAL	DATPTR
	GLOBAL	FNPTR
	GLOBAL	PROPTR
	GLOBAL	STAVAR
	GLOBAL	OC
	GLOBAL	PC
	GLOBAL	DYNVAR
	GLOBAL	CURLIN
	GLOBAL	STACK_TOP
	GLOBAL	USER
	GLOBAL	PATHBUF
	GLOBAL	DIRFIB

	GLOBAL	DOS_VER
	GLOBAL	FILE_HANDLE
	GLOBAL	FILE_MAXSIZE
	GLOBAL	FILE_BUFADRS
	GLOBAL	REQ_BYTES
	GLOBAL	DOS2_HANDLES
	GLOBAL	DOS2_EOF
	GLOBAL	DOS2_IOBUF
	GLOBAL	PATHBUF2

	ORG $5000


;
;n.b. ACCS, BUFFER & STAVAR must be on page boundaries.
;

ACCS:	DEFS	256		;STRING ACCUMULATOR
BUFFER:	DEFS	256		;STRING INPUT BUFFER
STAVAR:	DEFS	27*4		;STATIC VARIABLES
OC	EQU	STAVAR+15*4	;CODE ORIGIN (O%)
PC	EQU	STAVAR+16*4	;PROGRAM COUNTER (P%)
DYNVAR:	DEFS	54*2		;DYN. VARIABLE POINTERS
FNPTR:	DEFS	2		;DYN. FUNCTION POINTER
PROPTR:	DEFS	2		;DYN. PROCEDURE POINTER
;
PAGE:	DEFS	2		;START OF USER PROGRAM
LOMEM:	DEFS	2		;START OF DYN. STORAGE
FREE:	DEFS	2		;FIRST FREE-SPACE BYTE
HIMEM:	DEFS	2		;FIRST BYTE ABOVE STACK
LIBASE:	DEFS	2		;START OF FIRST LIBRARY
;
TRACEN:	DEFS	2		;TRACE FLAG AND NUMBER
AUTONO:	DEFS	2		;AUTO FLAG AND NUMBER
ERRTRP:	DEFS	2		;ON ERROR STMT POINTER \
ONERSP:	DEFS	2		;ON ERROR LOCAL STKPTR /
ERRTXT:	DEFS	2		;ERROR MESSAGE POINTER
DATPTR:	DEFS	2		;DATA POINTER
ERL:	DEFS	2		;LINE NO OF LAST ERROR
CURLIN:	DEFS	2		;POINTER TO CURRENT LINE
RANDOM:	DEFS	5		;RANDOM NUMBER
COUNT:	DEFS	1		;PRINT POSITION
WIDTH:	DEFS	1		;PRINT WIDTH
ERR:	DEFS	1		;ERROR NUMBER
LISTON:	DEFS	1		;LISTO & OPT FLAG
INCREM:	DEFS	1		;AUTO INCREMENT
; OS WORK AREAA
FILE_HANDLE:	DEFS	1		;MSX-DOS2 file handle used by OSLOAD
FILE_BUFADRS:	DEFS	2		; バッファのアドレス保存用
FILE_MAXSIZE:	DEFS	2		; 最大読み込みバイト数
REQ_BYTES:      DEFS    2       ; 読み込み要求バイト数
DOS2_HANDLES:	DEFS	9		; DOS2 file handles, indexed by BASIC channel
DOS2_EOF:	DEFS	9		; EOF flags, indexed by BASIC channel
DOS2_IOBUF:	DEFS	1		; Single-byte BGET/BPUT transfer buffer
PATHBUF:	DEFS	64		;PATH WORK BUFFER FOR MSX-DOS2 / SUBDIR SUPPORT
PATHBUF2:	DEFS	64		;Second pathname for MSX-DOS2 rename
DOS_VER:	DEFS	1		;MSX-DOS VERSION
DIRFIB:	DEFS	64		;MSX-DOS2 FFIRST/FNEXT file information block
;-------
USER:	;END
